let
    Source = Excel.CurrentWorkbook(){[Name="Table1"]}[Content],
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Customer ID", Int64.Type}, {"Customer Date of Birth", type date}, {"Email", type text}, {"Gender", type text}, {"Location", type text}, {"Product Category", type text}, {"Product Type", type text}, {"Product Name", type text}, {"Product Quantity", Int64.Type}, {"Cost Price", Int64.Type}, {"Selling Price", Int64.Type}, {"Purchase Date", type date}, {"Customer Loyalty Card", Int64.Type}, {"Age", Int64.Type}}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "Email", Splitter.SplitTextByDelimiter("@", QuoteStyle.Csv), {"Email.1", "Email.2"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Email.1", type text}, {"Email.2", type text}}),
    #"Split Column by Delimiter1" = Table.SplitColumn(#"Changed Type1", "Email.1", Splitter.SplitTextByDelimiter(".", QuoteStyle.Csv), {"Email.1.1", "Email.1.2"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"Email.1.1", type text}, {"Email.1.2", type text}}),
    #"Capitalized Each Word" = Table.TransformColumns(#"Changed Type2",{{"Email.1.1", Text.Proper, type text}, {"Email.1.2", Text.Proper, type text}}),
    #"Merged Columns" = Table.CombineColumns(#"Capitalized Each Word",{"Email.1.1", "Email.1.2"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"Full Name"),
    #"Removed Other Columns" = Table.SelectColumns(#"Merged Columns",{"Customer ID", "Customer Date of Birth", "Full Name", "Gender", "Location", "Product Category", "Product Type", "Product Name", "Product Quantity", "Cost Price", "Selling Price", "Purchase Date", "Customer Loyalty Card", "Age"}),
    #"Trimmed Text" = Table.TransformColumns(#"Removed Other Columns",{{"Product Name", Text.Trim, type text}}),
    #"Inserted Year" = Table.AddColumn(#"Trimmed Text", "Year", each Date.Year([Purchase Date]), Int64.Type),
    #"Renamed Columns" = Table.RenameColumns(#"Inserted Year",{{"Year", "Year of Purchase"}}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns",{{"Year of Purchase", type text}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type3",{"Customer ID", "Customer Date of Birth", "Full Name", "Gender", "Location", "Product Category", "Product Type", "Product Name", "Product Quantity", "Cost Price", "Selling Price", "Purchase Date", "Year of Purchase", "Customer Loyalty Card", "Age"}),
    #"Added Conditional Column" = Table.AddColumn(#"Reordered Columns", "Have Loyalty Card", each if [Customer Loyalty Card] = 0 then "No" else "Yes"),
    #"Reordered Columns1" = Table.ReorderColumns(#"Added Conditional Column",{"Customer ID", "Customer Date of Birth", "Full Name", "Gender", "Location", "Product Category", "Product Type", "Product Name", "Product Quantity", "Cost Price", "Selling Price", "Purchase Date", "Year of Purchase", "Customer Loyalty Card", "Have Loyalty Card", "Age"}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Reordered Columns1",{{"Have Loyalty Card", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type4",{"Customer Loyalty Card"}),
    #"Split Column by Delimiter2" = Table.SplitColumn(#"Removed Columns", "Location", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), {"Location.1", "Location.2"}),
    #"Changed Type5" = Table.TransformColumnTypes(#"Split Column by Delimiter2",{{"Location.1", type text}, {"Location.2", type text}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type5",{{"Location.1", "Country"}, {"Location.2", "Region"}}),
    #"Changed Type6" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Customer ID", type text}, {"Cost Price", Currency.Type}, {"Selling Price", Currency.Type}}),
    #"Added Prefix" = Table.TransformColumns(#"Changed Type6", {{"Customer ID", each "ZSD" & _, type text}}),
    #"Added Custom" = Table.AddColumn(#"Added Prefix", "CostPerOrder", each [Product Quantity]*[Cost Price]),
    #"Changed Type7" = Table.TransformColumnTypes(#"Added Custom",{{"CostPerOrder", Currency.Type}}),
    #"Reordered Columns2" = Table.ReorderColumns(#"Changed Type7",{"Customer ID", "Customer Date of Birth", "Full Name", "Gender", "Country", "Region", "Product Category", "Product Type", "Product Name", "Product Quantity", "Cost Price", "Selling Price", "CostPerOrder", "Purchase Date", "Year of Purchase", "Have Loyalty Card", "Age"}),
    #"Inserted Multiplication" = Table.AddColumn(#"Reordered Columns2", "Multiplication", each [Selling Price] * [Product Quantity], Currency.Type),
    #"Reordered Columns3" = Table.ReorderColumns(#"Inserted Multiplication",{"Customer ID", "Customer Date of Birth", "Full Name", "Gender", "Country", "Region", "Product Category", "Product Type", "Product Name", "Product Quantity", "Cost Price", "Selling Price", "CostPerOrder", "Multiplication", "Purchase Date", "Year of Purchase", "Have Loyalty Card", "Age"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Reordered Columns3",{{"Multiplication", "SalesPerOrder"}}),
    #"Inserted Subtraction" = Table.AddColumn(#"Renamed Columns2", "Subtraction", each [SalesPerOrder] - [CostPerOrder], Currency.Type),
    #"Reordered Columns4" = Table.ReorderColumns(#"Inserted Subtraction",{"Customer ID", "Customer Date of Birth", "Full Name", "Gender", "Country", "Region", "Product Category", "Product Type", "Product Name", "Product Quantity", "Cost Price", "Selling Price", "CostPerOrder", "SalesPerOrder", "Subtraction", "Purchase Date", "Year of Purchase", "Have Loyalty Card", "Age"}),
    #"Renamed Columns3" = Table.RenameColumns(#"Reordered Columns4",{{"Subtraction", "Profit Per Order"}, {"SalesPerOrder", "Sales Per Order"}, {"CostPerOrder", "Cost Per Order"}})
in
    #"Renamed Columns3"